#!/bin/sh
# Cervus build configurator.
#
# Ninja does not scan directories -- it needs a build.ninja listing every
# source file and rule. This script is that "configure" step: it walks the
# tree and emits build.ninja. Ninja then handles incremental rebuilds (via
# gcc depfiles, so header edits are tracked properly) and parallelism
# (`ninja -j N`).
#
# The heavy, cacheable work (kernel, libc, libcervus, userland programs) lives
# entirely in Ninja. One-time / network / source-patching steps (fetching
# deps, limine, building tcc) are delegated to builder/bootstrap.sh and gated
# behind stamp files so they run at most once.
#
# Usage:  builder/configure.sh   (run from anywhere; cd's to repo root)

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

BUILDDIR=.ninja
STAMPS=.ninja/stamps

SYSLIB=usr/sysroot/usr/lib
CRT0=$SYSLIB/crt0.o
LIBCERVUS_A=$SYSLIB/libcervus.a
LINKER_SCRIPT=kernel/linker-scripts/x86_64.lds

# --- Flags: lifted verbatim from build.c so output stays byte-identical. -----
KERNEL_BASE="-g -O2 -pipe -Wall -Wextra -std=gnu11 -nostdinc -ffreestanding \
-fno-stack-protector -fno-stack-check -fno-lto -fno-PIC \
-ffunction-sections -fdata-sections \
-m64 -march=x86-64 -mabi=sysv -mcmodel=kernel \
-mno-red-zone -fcf-protection=none"
KERNEL_CORE="$KERNEL_BASE -mgeneral-regs-only -mno-sse -mno-sse2 -mno-mmx -mno-3dnow"
KERNEL_SSE="$KERNEL_BASE -msse -msse2 -mfpmath=sse -mno-mmx -mno-3dnow"
KERNEL_CPP="-I kernel/src -I libc/include \
-I limine-tools/limine-protocol/include \
-isystem limine-tools/freestnd-c-hdrs/include"

# A file uses the SSE flag set if any of these appears in its path.
SSE_FILES="sse.c fpu.c fabs.c pow.c pow10.c serial.c snprintf.c printf.c"

LIBCERVUS_CFLAGS="-ffreestanding -nostdlib -static -fno-stack-protector \
-mno-red-zone -fno-pie -fno-pic -O0 -g -Wall -Wextra \
-nostdinc -isystem usr/sysroot/usr/include -I usr/lib/libcervus/include"

APP_CFLAGS="-ffreestanding -nostdlib -static -fno-stack-protector -fno-pie -fno-pic \
-msse -msse2 -mfpmath=sse -mno-avx -mno-avx2 -mno-red-zone -O0 -g \
-nostdinc -isystem usr/sysroot/usr/include -Wl,-Ttext-segment=0x401000"

DEPS_STAMP=$STAMPS/deps
LIMINE_STAMP=$STAMPS/limine
TCC_STAMP=$STAMPS/tcc

# --- helpers ----------------------------------------------------------------
# obj/<category>/<flattened-path>.o   (same scheme as build.c)
obj_for() {  # $1=src  $2=category
    printf 'obj/%s/%s.o' "$2" "$(printf '%s' "$1" | tr './' '__')"
}

is_sse() {  # $1=path ; returns 0 if it should build with SSE flags
    for s in $SSE_FILES; do
        case "$1" in *"$s"*) return 0 ;; esac
    done
    return 1
}

# --- linker script (deterministic; rewrite only when changed so ninja does
#     not relink the kernel on every configure) --------------------------------
mkdir -p "$(dirname "$LINKER_SCRIPT")"
_lds_tmp=$(mktemp)
cat > "$_lds_tmp" <<'LDS'
OUTPUT_FORMAT(elf64-x86-64)
ENTRY(kernel_main)
PHDRS {
    limine_requests PT_LOAD;
    text PT_LOAD;
    rodata PT_LOAD;
    data PT_LOAD;
}
SECTIONS {
    . = 0xffffffff80000000;
    .limine_requests : {
        KEEP(*(.limine_requests_start))
        KEEP(*(.limine_requests))
        KEEP(*(.limine_requests_end))
    } :limine_requests
    . = ALIGN(CONSTANT(MAXPAGESIZE));
    .text : {
        __start_isr_handlers = .;
        KEEP(*(.isr_handlers))
        __stop_isr_handlers = .;
        __start_irq_handlers = .;
        KEEP(*(.irq_handlers))
        __stop_irq_handlers = .;
        *(.text .text.*)
    } :text
    . = ALIGN(CONSTANT(MAXPAGESIZE));
    .rodata : { *(.rodata .rodata.*) } :rodata
    .note.gnu.build-id : { *(.note.gnu.build-id) } :rodata
    . = ALIGN(CONSTANT(MAXPAGESIZE));
    .data : {
        *(.data .data.*)
        . = ALIGN(4096);
        __percpu_start = .;
        KEEP(*(.percpu.head))
        KEEP(*(.percpu .percpu.*))
        . = ALIGN(4096);
        __percpu_end = .;
    } :data
    .bss : { *(.bss .bss.*) *(COMMON) } :data
    /DISCARD/ : { *(.eh_frame*) *(.note .note.*) }
}
LDS
if ! cmp -s "$_lds_tmp" "$LINKER_SCRIPT" 2>/dev/null; then
    mv "$_lds_tmp" "$LINKER_SCRIPT"
else
    rm -f "$_lds_tmp"
fi

# --- generate build.ninja ---------------------------------------------------
N=build.ninja
{
cat <<EOF
# Auto-generated by builder/configure.sh -- do not edit by hand.
ninja_required_version = 1.10
builddir = $BUILDDIR

rule cc_core
  command = gcc $KERNEL_CORE $KERNEL_CPP -MMD -MF \$out.d -c \$in -o \$out
  description = CC(core)  \$in
  depfile = \$out.d
  deps = gcc

rule cc_sse
  command = gcc $KERNEL_SSE $KERNEL_CPP -MMD -MF \$out.d -c \$in -o \$out
  description = CC(sse)   \$in
  depfile = \$out.d
  deps = gcc

rule asm
  command = nasm -g -F dwarf -f elf64 \$in -o \$out
  description = AS        \$in

rule asm_bare
  command = nasm -f elf64 \$in -o \$out
  description = AS        \$in

rule psf
  command = builder/mk_psf.sh \$in \$out
  description = PSF       \$in

rule cc_lib
  command = gcc $LIBCERVUS_CFLAGS -MMD -MF \$out.d -c \$in -o \$out
  description = CC(lib)   \$in
  depfile = \$out.d
  deps = gcc

rule cc_app
  command = gcc $APP_CFLAGS -MMD -MF \$out.d -o \$out \$in $CRT0 $LIBCERVUS_A
  description = CCLD(app) \$out
  depfile = \$out.d
  deps = gcc

rule ar
  command = rm -f \$out && ar rcs \$out \$in
  description = AR        \$out

rule link_kernel
  command = ld -m elf_x86_64 -nostdlib -static -z max-page-size=0x1000 --gc-sections -T $LINKER_SCRIPT -o \$out \$in
  description = LINK      \$out

rule bootstrap
  command = builder/bootstrap.sh \$step && mkdir -p $STAMPS && touch \$out
  description = BOOTSTRAP \$step
  restat = 1
  pool = console

rule initramfs
  command = builder/mk_initramfs.sh && touch \$out
  description = INITRAMFS \$out
  pool = console

rule iso
  command = builder/mk_iso.sh && touch \$out
  description = ISO       \$out
  pool = console

# --- one-time bootstrap stamps ---------------------------------------------
build $DEPS_STAMP: bootstrap
  step = deps
build $LIMINE_STAMP: bootstrap
  step = limine

EOF

# --- libcervus -> libcervus.a + crt0.o -------------------------------------
LIB_OBJS=""
for src in $(find usr/lib/libcervus -name '*.c' | sort); do
    obj=$(obj_for "$src" libcervus)
    printf 'build %s: cc_lib %s\n' "$obj" "$src"
    LIB_OBJS="$LIB_OBJS $obj"
done
printf 'build obj/libcervus/setjmp.o: asm_bare usr/lib/libcervus/setjmp.asm\n'
printf 'build %s: asm_bare usr/lib/libcervus/crt0.asm\n' "$CRT0"
printf 'build %s: ar%s obj/libcervus/setjmp.o\n\n' "$LIBCERVUS_A" "$LIB_OBJS"

# --- userland programs -> *.elf --------------------------------------------
PROG_DEPS="$CRT0 $LIBCERVUS_A"
ALL_ELFS=""
for dir in usr/apps usr/bin usr/installer; do
    [ -d "$dir" ] || continue
    for src in "$dir"/*.c; do
        [ -e "$src" ] || continue
        base=$(basename "$src" .c)
        case "$base" in .*) continue ;; esac
        elf="$dir/$base.elf"
        printf 'build %s: cc_app %s | %s\n' "$elf" "$src" "$PROG_DEPS"
        ALL_ELFS="$ALL_ELFS $elf"
    done
done
printf '\n'

# --- tcc (built by the legacy patcher; needs libcervus + sysroot headers) ---
# order-only on the libs: they must exist first, but the tcc bootstrap must not
# re-run just because libcervus.a was rebuilt.
printf 'build %s: bootstrap || %s\n  step = tcc\n\n' "$TCC_STAMP" "$PROG_DEPS"

# --- kernel + libc -> bin/kernel -------------------------------------------
KOBJS=""
for src in $(find kernel/src \( -name '*.c' -o -name '*.asm' -o -name '*.psf' \) | sort) \
           $(find libc/src -name '*.c' | sort); do
    case "$src" in
        kernel/*) cat=kernel ;;
        libc/*)   cat=libc ;;
        *)        cat=other ;;
    esac
    obj=$(obj_for "$src" "$cat")
    case "$src" in
        *.asm) printf 'build %s: asm %s\n' "$obj" "$src" ;;
        *.psf) printf 'build %s: psf %s\n' "$obj" "$src" ;;
        *)
            if is_sse "$src"; then rule=cc_sse; else rule=cc_core; fi
            printf 'build %s: %s %s || %s\n' "$obj" "$rule" "$src" "$DEPS_STAMP" ;;
    esac
    KOBJS="$KOBJS $obj"
done
printf 'build bin/kernel: link_kernel%s | %s\n\n' "$KOBJS" "$LINKER_SCRIPT"

# --- initramfs.tar ---------------------------------------------------------
printf 'build initramfs.tar: initramfs | bin/kernel %s %s %s usr/apps/init.elf%s\n\n' \
    "$LIBCERVUS_A" "$TCC_STAMP" "$LIMINE_STAMP" "$ALL_ELFS"

# --- ISO -------------------------------------------------------------------
printf 'build %s/iso.stamp: iso | bin/kernel initramfs.tar usr/apps/init.elf %s\n' \
    "$BUILDDIR" "$LIMINE_STAMP"
printf 'build iso: phony %s/iso.stamp\n\n' "$BUILDDIR"

# --- aliases + default -----------------------------------------------------
printf 'build kernel: phony bin/kernel\n'
printf 'build libcervus: phony %s\n' "$LIBCERVUS_A"
printf 'build apps: phony%s\n' "$ALL_ELFS"
printf 'default initramfs.tar\n'
} > "$N"

echo "Wrote $N"
